name: lint protobuf

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: bufbuild/buf-setup-action@v0.3.1
      - name: lint
        run: make all
